apiVersion: v1
kind: Pod
metadata:
  name: nvidia-test
spec:
  #runtimeClassName: nvidia
  containers:
  - name: nvidia-test
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    command: ["nvidia-smi"]
